In [1]:
import numpy as np

## creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [6]:
a[2]

3

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [8]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## multi-dimensional arrays

In [14]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
n = np.array([[1, 2, 3], 
        [1, 2, 3],
        [1, 2, 3]]
)
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 1,  2,  3],
       [ 1,  2,  3]])

In [22]:
n[2] = [10, 20, 30]
n

array([[ 1, 20,  3],
       [ 1,  2,  3],
       [10, 20, 30]])

In [23]:
n[:, 2] = [100, 200, 300]
n

array([[  1,  20, 100],
       [  1,   2, 200],
       [ 10,  20, 300]])

## randomly generated arrays

In [26]:
np.random.seed(10)
np.random.rand(5, 2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [ ]:
# normal distribution
np.random.seed(10)
np.random.randn(5, 2)

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [28]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## element-wise operations

In [30]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
b = a + 1
b

array([1, 2, 3, 4, 5])

##  comparison operations

In [33]:
a >= 2

array([False, False,  True,  True,  True])

In [34]:
a < b

array([ True,  True,  True,  True,  True])

In [35]:
a[a >= 2]

array([2, 3, 4])

## summarizing operations

In [36]:
a.min()

0

In [37]:
a.sum()

10

In [38]:
a.mean()

2.0