In [1]:
import numpy as np

## Vector opeations

In [2]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [5]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [6]:
u + v

array([3, 4, 5, 8])

### Vector-vector multiplication

In [7]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

In [8]:
vector_vector_multiplication(u, v)

14.0

In [9]:
u.dot(v)

14

### Matrix-vector multiplication

In [12]:
U = np.array([[2, 4, 5, 6],
              [1, 2, 1, 2],
              [3, 1, 2, 1],
              
])
v = np.array([1, 0.5, 2, 1])

In [24]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    n = u.shape[0]
    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [14]:
matrix_vector_multiplication(U, v)

array([20. ,  6. ,  8.5])

In [15]:
U.dot(v)

array([20. ,  6. ,  8.5])

### Matrix-matrix multiplication

In [20]:
U = np.array([[2, 4, 5, 6],
              [1, 2, 1, 2],
              [3, 1, 2, 1],
              
])
V = np.array([[1, 1, 1],
              [0, 0.5, 1],
              [0, 2, 1],
              [2, 1, 0],
              
])

In [26]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros(( num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [27]:
matrix_matrix_multiplication(U, V)


array([[14. , 20. , 11. ],
       [ 5. ,  6. ,  4. ],
       [ 5. ,  8.5,  6. ]])

In [23]:
U.dot(V)

array([[14. , 20. , 11. ],
       [ 5. ,  6. ,  4. ],
       [ 5. ,  8.5,  6. ]])

## Identity matrix

In [32]:
I =np.eye(3)
I  

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
V.dot(I)

array([[1. , 1. , 1. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Inverse matrix

In [35]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 1. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [38]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -0.66666667, -0.33333333],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [39]:
Vs_inv.dot(Vs)

array([[1.00000000e+00, 1.11022302e-16, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])